Repository shinhan-hackathon-the-guardians/frontend, pull requests merged in 2024-08, with the labels that each got.

#6 Setting/#5
  src/components/.gitkeep
  src/constant/.gitkeep
  src/hooks/.gitkeep
  src/pages/.gitkeep
  src/services/.gitkeep
  src/stores/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
Labels: ⚙ Setting

#7 #4 [Feat] 헤더 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Header/HeaderBackChatNotify.tsx
  src/components/Header/HeaderBackSetting.tsx
  src/components/Header/HeaderLogoChatNotify.tsx
Labels: ✨ Feature

#11 #10 [Setting] tailwind color setting
  package-lock.json
  package.json
  src/App.tsx
  src/components/.gitkeep
  src/components/AddGroupMember/InputField.tsx
  src/components/AddGroupMember/SelectField.tsx
  src/constant/.gitkeep
  src/constant/relationship.ts
  src/pages/.gitkeep
  src/pages/AddGroupMemberPage.tsx
  src/routes/router.tsx
  tailwind.config.js
Labels: ⚙ Setting

#16 Feat/#12
  src/assets/images/chat.png
  src/components/Header/HeaderLogoChatNotify.tsx
  src/components/Notification/PaymentRequestModal.tsx
  src/components/Notification/UnreadSticker.tsx
  src/pages/MainPage.tsx
  src/pages/PaymentRequestPage.tsx
  src/pages/VerificationCodePage.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#17 #14 [Feat] 그룹원 목록 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/groupList/기타.svg
  src/assets/images/groupList/아버지.svg
  src/assets/images/groupList/어머니.svg
  src/assets/images/groupList/자녀.svg
  src/assets/images/groupList/할머니.svg
  src/assets/images/groupList/할아버지.svg
  src/assets/images/groupList/형제.svg
  src/components/GroupMemberList/GroupInfo.tsx
  src/components/GroupMemberList/GroupMemberItem.tsx
  src/components/GroupMemberList/GroupMemberList.tsx
  src/components/GroupMemberList/GroupMemberOptions.tsx
  src/components/common/Button.tsx
  src/constant/common.ts
  src/pages/AddGroupMemberPage.tsx
  src/pages/GroupMemberListPage.tsx
  src/routes/router.tsx
  src/services/.gitkeep
  src/services/groupMemberService.ts
  src/types/.gitkeep
  src/types/Member.ts
  src/utils/.gitkeep
  src/utils/data.ts
  tailwind.config.js
Labels: ✨ Feature

#19 #18 [Feat] 문제은행 페이지 구현
  src/assets/fonts/goorm-fonts.css
  src/assets/fonts/goorm-sans-bold.woff2
  src/assets/fonts/goorm-sans-medium.woff2
  src/assets/fonts/goorm-sans-regular.woff2
  src/components/Question/AnswerButton.tsx
  src/components/Question/Explanation.tsx
  src/components/Question/ProgressBar.tsx
  src/components/Question/QuestionInfo.tsx
  src/index.css
  src/pages/QuestionBankPage.tsx
  src/routes/router.tsx
  src/services/axiosInstance.ts
  src/services/groupMemberService.ts
  src/services/questionService.ts
  src/types/Question.ts
  src/types/Response.ts
  src/utils/data.ts
  tailwind.config.js
Labels: ✨ Feature

#22 #20 [Feat] 가디언 시험 페이지
  src/components/Question/AnswerButton.tsx
  src/components/Question/ProgressBar.tsx
  src/components/Question/QuestionInfo.tsx
  src/components/Question/ResultModal.tsx
  src/constant/common.ts
  src/index.css
  src/pages/GuardianExamPage.tsx
  src/routes/router.tsx
  src/utils/data.ts
  tailwind.config.js
Labels: ✨ Feature

#24 #23 [Feat] router navigation 연결 및 경고 모달
  src/assets/css/Loading.css
  src/assets/fonts/goorm-font.css
  src/components/Header/HeaderBackChatNotify.tsx
  src/components/Header/HeaderBackSetting.tsx
  src/components/Header/HeaderLogoChatNotify.tsx
  src/components/Question/AnswerButton.tsx
  src/components/Question/ResultModal.tsx
  src/components/Question/WarningModal.tsx
  src/components/common/Loading.tsx
  src/hooks/.gitkeep
  src/hooks/useNavigation.ts
  src/index.css
  src/pages/GuardianExamPage.tsx
  src/pages/MainPage.tsx
  src/pages/QuestionBankPage.tsx
  src/routes/router.tsx
  src/types/AnswerButton.ts
  src/utils/cn.ts
Labels: ✨ Feature

#26 [Feat] 회원가입 로그인 화면 구현
  package-lock.json
  package.json
  src/assets/fonts/goorm-font.css
  src/hooks/useNavigation.ts
  src/index.css
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#30 [Feat]: 그룹 설정 페이지 구현
  src/App.tsx
  src/components/Header/HeaderBackChatNotify.tsx
  src/components/Header/HeaderBackSetting.tsx
  src/hooks/useNavigation.ts
  src/pages/GroupSettingsPage.tsx
  src/routes/router.tsx
  src/services/groupSettingsService.ts
  src/types/GroupSettings.ts
Labels: ✨ Feature

#32 #31 [Feat] 파비콘 및 타이틀, 스플래시 추가
  index.html
  package-lock.json
  package.json
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  src/App.tsx
  src/assets/images/splash.png
  src/components/Header/HeaderLogoChatNotify.tsx
  src/hooks/useNavigation.ts
  src/pages/SplashScreen.tsx
  src/routes/router.tsx
  src/stores/.gitkeep
  src/stores/userAuthStore.ts
  src/types/User.ts
Labels: ✨ Feature

#34 [Html&CSS] 메인 디자인 수정
  src/assets/images/chatbot.png
  src/assets/images/guardianBadge.png
  src/components/Header/HeaderBackChatNotify.tsx
  src/components/Header/HeaderLogoChatNotify.tsx
  src/hooks/useNavigation.ts
  src/pages/ChatBotPage.tsx
  src/pages/MainPage.tsx
  src/pages/PaymentRequestPage.tsx
  src/routes/router.tsx
  src/services/groupMemberService.ts
  src/types/Member.ts
  src/utils/data.ts
Labels: 🎨 Html&css

#35 [Fix] #27 - 메인 이미지 소스 경로 수정
  src/pages/MainPage.tsx
Labels: 🐞 BugFix

#38 [Design]: 회원가입 및 로그인 폼 디자인 수정
  src/App.tsx
  src/components/Question/ResultModal.tsx
  src/components/common/InputField.tsx
  src/components/common/SelectField.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 🎨 Html&css

#41 [Feat] 챗봇 페이지 구현
  src/components/Header/HeaderBack.tsx
  src/pages/ChatBotPage.tsx
  src/pages/MainPage.tsx
Labels: ✨ Feature

#43 [Feat] #42 InputField focus border 변경
  src/components/common/InputField.tsx
  src/components/common/SelectField.tsx
  src/pages/SignUpPage.tsx
Labels: 🎨 Html&css

#49 [Feat/#48] 전체적인 디자인 수정
  src/components/Question/AnswerButton.tsx
  src/components/Question/ResultModal.tsx
  src/pages/ChatBotPage.tsx
  src/pages/GuardianExamPage.tsx
  src/pages/MainPage.tsx
  src/pages/QuestionBankPage.tsx
Labels: 🎨 Html&css

#56 #40 [Feat] 로그인/회원가입/로그아웃 연결
  .hintrc
  src/components/Header/HeaderLogoChatNotify.tsx
  src/main.tsx
  src/pages/GroupMemberListPage.tsx
  src/pages/GuardianExamPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/QuestionBankPage.tsx
  src/pages/SignUpPage.tsx
  src/services/axiosInstance.ts
  src/services/groupMemberService.ts
  src/services/userAuthService.ts
  src/stores/userAuthStore.ts
  src/types/User.ts
Labels: ✨ Feature

#57 #50 [Feat] 그룹 관련 api함수 구현
  src/pages/AddGroupMemberPage.tsx
  src/pages/GroupMemberListPage.tsx
  src/services/groupMemberService.ts
Labels: ✨ Feature

#59 [BugFix]: 프론트 배포 store 겹침 해결
  src/pages/GroupMemberListPage.tsx
Labels: 🐞 BugFix

#60 [Feat]: 시험 관련 api 함수 구현
  src/components/Question/ResultModal.tsx
  src/constant/common.ts
  src/pages/GuardianExamPage.tsx
  src/pages/QuestionBankPage.tsx
  src/services/questionService.ts
Labels: ✨ Feature

#61 [BugFix]: import 에러 수정
  src/pages/GuardianExamPage.tsx
Labels: 🐞 BugFix

#62 [Feat]: 시험 관련 api 연동
  src/services/questionService.ts
Labels: ✨ Feature

#63 #50 [Feat]: 유저 로그인 상태 저장
  src/components/GroupMemberList/GroupMemberList.tsx
  src/pages/GroupMemberListPage.tsx
  src/pages/MainPage.tsx
  src/pages/SplashScreen.tsx
  src/services/groupMemberService.ts
  src/stores/userAuthStore.ts
Labels: ✨ Feature

#67 #50 [Feat]: 그룹 리스트 불러오기
  src/components/GroupMemberList/GroupMemberItem.tsx
  src/pages/GroupMemberListPage.tsx
  src/services/groupMemberService.ts
  src/types/Member.ts
  src/types/Response.ts
Labels: ✨ Feature

#68 #50 [BugFix]: member type level 변경 오류 수정
  src/utils/data.ts
Labels: 🐞 BugFix

#71 [Feat/#54] 챗봇 서비스
  package-lock.json
  package.json
  src/pages/ChatBotPage.tsx
  src/services/axiosInstance.ts
  src/services/chatBotService.ts
  src/types/Response.ts
Labels: ✨ Feature

#74 [Feat/#73] 로그인 디자인 수정
  src/pages/LoginPage.tsx
Labels: 🎨 Html&css

#76 [Design/#75] 회원가입 전체적 디자인 수정
  src/components/common/InputField.tsx
  src/components/common/SelectField.tsx
  src/pages/SignUpPage.tsx
Labels: 🎨 Html&css

#79 #51 [Feat]: 그룹 및 그룹 세팅에 관한 api 구현
  .hintrc
  package-lock.json
  src/components/GroupMemberList/GroupMemberItem.tsx
  src/components/Header/HeaderBackSetting.tsx
  src/components/common/SelectField.tsx
  src/constant/period.ts
  src/constant/role.ts
  src/constant/term.ts
  src/hooks/useNavigation.ts
  src/pages/GroupMemberListPage.tsx
  src/pages/GroupSettingsPage.tsx
  src/pages/MainPage.tsx
  src/pages/MemberSettingsPage.tsx
  src/routes/router.tsx
  src/services/groupMemberService.ts
  src/services/groupSettingsService.ts
  src/services/memberSettingsService.ts
  src/types/GroupSettings.ts
  src/types/Response.ts
  src/types/User.ts
Labels: ✨ Feature

#81 메인 알림 화면 구현
  package-lock.json
  package.json
  src/components/Header/HeaderBackChatNotify.tsx
  src/components/Header/HeaderLogoChatNotify.tsx
  src/components/Question/WarningModal.tsx
  src/hooks/useNavigation.ts
  src/mock/mock.ts
  src/pages/LoginPage.tsx
  src/pages/NotificationPage.tsx
  src/routes/router.tsx
  src/services/notificationService.ts
Labels: ✨ Feature

#83 [Fix] baseURL 수정
  src/services/axiosInstance.ts
Labels: 🐞 BugFix

#85 [Feat] 알림 페이지 예외 처리
  src/components/Notification/PaymentRequestModal.tsx
  src/mock/mock.ts
  src/pages/NotificationPage.tsx
Labels: ✨ Feature

#89 [Fix] #86 - 빌드 오류 수정
  src/mock/mock.ts
  src/pages/NotificationPage.tsx
Labels: 🐞 BugFix

#91 [Fix] App 모달 오류 수정
  src/App.tsx
Labels: 🐞 BugFix

#87 [Feat]: 가디언 평가 시 배지 바로 반영
  src/components/Question/ResultModal.tsx
  src/pages/MainPage.tsx
  src/services/userAuthService.ts
  src/stores/userAuthStore.ts
Labels: ✨ Feature

#78 [Feat/#72] 결제 페이지: 입금, 출금, 이제, 결제
  src/assets/images/shinhan_log_white.png
  src/components/Header/HeaderLogoChatNotify.tsx
  src/components/Question/WarningModal.tsx
  src/components/common/InputField.tsx
  src/pages/MainPage.tsx
  src/pages/TransactionPage.tsx
  src/routes/router.tsx
  src/services/axiosInstance.ts
  src/services/transactionService.tsx
  src/types/Response.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&css

#94 [Feat]: 그룹원 초대 폼 전화번호 양식 수정
  src/pages/AddGroupMemberPage.tsx
  src/services/groupMemberService.ts
Labels: ✨ Feature, 🎨 Html&css

#97 #96 [Fix] 세부 디테일 수정
  src/assets/images/guardianBadgeRe.png
  src/components/GroupMemberList/GroupMemberItem.tsx
  src/pages/MainPage.tsx
  src/pages/NotificationPage.tsx
  src/services/notificationService.ts
  src/types/Member.ts
Labels: 🎨 Html&css, 🔨 Refactor

#98 [Feat/#92] 실시간 계좌 잔액 조회 기능
  src/pages/TransactionPage.tsx
  src/services/transactionService.tsx
Labels: ✨ Feature

#102 [Fix] #101 - case 오류 수정
  src/App.tsx
Labels: 🐞 BugFix

#103 #96 [Fix] 그룹원 추가 알림 리스트로 변환 및 ui 수정
  src/components/Header/HeaderBackChatNotify.tsx
  src/components/Header/HeaderBackSetting.tsx
  src/pages/MainPage.tsx
  src/pages/NotificationPage.tsx
  src/services/notificationService.ts
Labels: 🎨 Html&css, 🔨 Refactor

#106 #96 [Fix] 그룹원 초대 승낙 후 메인 업데이트
  src/pages/NotificationPage.tsx
  src/stores/userAuthStore.ts
Labels: ✨ Feature, 🔨 Refactor

#107 Fix/#101
  src/App.tsx
  src/components/Notification/FamilyInviteModal.tsx
Labels: 🐞 BugFix

#105 [Design/#104] 로그아웃 버튼 수정
  src/components/Header/HeaderLogoChatNotify.tsx
Labels: ✨ Feature

#109 [Feat] #200 모달 전부 완성
  src/App.tsx
  src/components/Notification/DepositModal.tsx
  src/components/Notification/PaymentFailureModal.tsx
  src/components/Notification/PaymentSuccessModal.tsx
  src/components/Notification/TransferFailureModal.tsx
  src/components/Notification/TransferSuccessModal.tsx
  src/components/Notification/WithdrawalFailureModal.tsx
  src/components/Notification/WithdrawalSuccessModal.tsx
Labels: ✨ Feature

#110 [Fix]: 고정 수정
  src/components/GroupMemberList/GroupMemberOptions.tsx
  src/components/Notification/WithdrawalSuccessModal.tsx
Labels: ✨ Feature
